[pytest]
testpaths = tests
pythonpath = .
addopts = --import-mode=importlib --cov --cov-report=term-missing --cov-fail-under=100
filterwarnings =
    ignore::DeprecationWarning
asyncio_mode = auto
norecursedirs =
    pykoplenti-master
